tailscale_authkey: >-
  {{ lookup('community.hashi_vault.hashi_vault',
    'secret=secret/data/tailscale:authkey token=' ~ vault_token ~ ' url=' ~ vault_addr) }}
vault_addr: "http://localhost:8200"
vault_token: "{{ lookup('env', 'VAULT_TOKEN') | default('myroot', true) }}"
