tailscale_authkey: >-
  {{ lookup('community.hashi_vault.hashi_vault',
    'secret=secret/secret/tailscale:authkey token=' ~ vault_token ~ ' url=' ~ vault_addr) }}
vault_addr: "http://192.168.50.169:8200"
vault_token: "{{ lookup('env', 'VAULT_TOKEN') }}"
