- name: Install dnsmasq
  apt:
    name: dnsmasq
    update_cache: yes

- name: Configure dnsmasq upstreams
  copy:
    dest: /etc/dnsmasq.d/upstreams.conf
    content: |
      server={{ dns_upstream_servers | join("\nserver=") }}

- name: Enable and start dnsmasq
  systemd:
    name: dnsmasq
    enabled: yes
    state: started
