# Example: Pull WireGuard keys/config from Vault
wg_private_key: >-
  {{ lookup('community.hashi_vault.hashi_vault',
    'secret=secrets/secret/wireguard:private_key token=' ~ vault_token ~ ' url=' ~ vault_addr) }}
wg_public_key_peer: >-
  {{ lookup('community.hashi_vault.hashi_vault',
    'secret=secret/data/wireguard:peer_public_key token=' ~ vault_token ~ ' url=' ~ vault_addr) }}
<<<<<<< HEAD
vault_addr: "http://192.168.50.169:8200"
vault_token: "{{ lookup('env', 'VAULT_TOKEN') }}"
=======
vault_addr: "http://localhost:8200"
vault_token: "{{ lookup('env', 'VAULT_TOKEN') | default('myroot', true) }}"
>>>>>>> dev
